version: '3'

services:
  eureka:
    image: heroes/eureka
    ports:
    - 8761:8761
  zuul:
    image: heroes/zuul
    ports:
    - 10000:10000
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
  auth:
    image: heroes/auth
    ports:
    - 10001:10001
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
  hero:
    image: heroes/hero
    ports:
    - 10002:10002
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
    deploy:
      replicas: 3